ARG GOVERSION=1.25.6

FROM golang:${GOVERSION}-bookworm AS build

ENV GO111MODULE=on
ENV GOPROXY=https://proxy.golang.org,direct

SHELL ["/bin/bash", "-c"]

ARG COSMOVISOR_VERSION

RUN GOBIN=/usr/bin go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@${COSMOVISOR_VERSION}

FROM debian:bookworm AS base
LABEL "org.opencontainers.image.source"="https://github.com/akash-network/cosmovisor"

COPY --from=build /usr/bin/cosmovisor /usr/bin
