name: release-cosmovisor

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - cosmovisor/v*

jobs:
  cosmovisor:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup env
      uses: c-py/action-dotenv-to-setenv@v3
      with:
        env-file: .env
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Fetch tag
      run: |
        echo "RELEASE_TAG=${GITHUB_REF#refs/tags/cosmovisor/}" >> $GITHUB_ENV
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/akash-network/cosmovisor-base
        # generate Docker tags based on the following events/attributes
        tags: |
          type=semver,priority=1000,pattern={{major}}.{{minor}}.{{patch}},prefix=v,value=${{ env.RELEASE_TAG }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile.cosmovisor
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          COSMOVISOR_VERSION=${{ env.COSMOVISOR_VERSION }}
          GO_VERSION=${{ env.GO_VERSION }}
